dictionaries = ["en_us"]
words = [
    "adva",
    "advapacs",
    "ahs",
    "dcm",
    "dicom",
    "egui",
    "pacs",
    "syntaxes",
    "wgpu",
]
flag_words = [
    "todo",
    "fixme",
]
ignore_paths = [
    "target/**/*",
    "**/*.json",
    ".git/**/*",
]
